"""Initial migration

Revision ID: b2a8e0953698
Revises: 
Create Date: 2025-01-24 08:26:01.864512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a8e0953698'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_name_parent', 'actions', ['name', 'parent_id'], unique=False)
    op.create_index(op.f('ix_actions_id'), 'actions', ['id'], unique=False)
    op.create_index(op.f('ix_actions_name'), 'actions', ['name'], unique=True)
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('coordinates', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_address_coordinates', 'addresses', ['coordinates'], unique=False)
    op.create_index(op.f('ix_addresses_address'), 'addresses', ['address'], unique=True)
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('telephone_number', sa.String(length=15), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_organisation_name_telephone', 'organisations', ['name', 'telephone_number'], unique=False)
    op.create_index(op.f('ix_organisations_id'), 'organisations', ['id'], unique=False)
    op.create_index(op.f('ix_organisations_name'), 'organisations', ['name'], unique=False)
    op.create_index(op.f('ix_organisations_telephone_number'), 'organisations', ['telephone_number'], unique=True)
    op.create_table('organizationactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizationactions_id'), 'organizationactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizationactions_id'), table_name='organizationactions')
    op.drop_table('organizationactions')
    op.drop_index(op.f('ix_organisations_telephone_number'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_name'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_id'), table_name='organisations')
    op.drop_index('ix_organisation_name_telephone', table_name='organisations')
    op.drop_table('organisations')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_address'), table_name='addresses')
    op.drop_index('ix_address_coordinates', table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_actions_name'), table_name='actions')
    op.drop_index(op.f('ix_actions_id'), table_name='actions')
    op.drop_index('ix_action_name_parent', table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
